/* eslint-disable @next/next/no-img-element */
import styles from "../styles/Layout.module.css";
import logo from "../public/logo.png";
import Head from "next/head";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faEtsy,
  faFacebookF,
  faInstagram,
  faPinterestP,
} from "@fortawesome/free-brands-svg-icons";

type Props = {
  children: JSX.Element | JSX.Element[];
  page?: string;
};

export default function Layout(props: Props) {
  return (
    <div className={styles.main_container}>
      <Head>
        <title>Qualis Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.navbar}>
        <div className={styles.flex_third}>
          <Link href="/services">
            <p className={styles.link} style={{ marginRight: "64px", borderBottom: props.page === "services" ? "2px solid black" : "none" }}>
              Services
            </p>
          </Link>
          <Link href="/about">
            <p className={styles.link} style={{ marginRight: "64px", borderBottom: props.page === "about" ? "2px solid black" : "none" }}>
              About
            </p>
          </Link>
          <Link href="/portfolio">
            <p className={styles.link} style={{borderBottom: props.page === "portfolio" ? "2px solid black" : "none"}}>Portfolio</p>
          </Link>
        </div>
        <div className={styles.flex_third} style={{ justifyContent: "center" }}>
          <Link href="/">
            <img src={logo.src} alt="Logo" className={styles.logo} />
          </Link>
        </div>
        <div
          className={styles.flex_third}
          style={{ justifyContent: "flex-end" }}
        >
          <Link href="/contact">
            <div className={styles.link_button}>
              <p className={styles.link} style={{borderBottom: props.page === "contact" ? "2px solid black" : "none"}}>Contact</p>
            </div>
          </Link>
        </div>
      </header>
      <main className={styles.content}>{props.children}</main>
      <footer className={styles.footer}>
        <div className={styles.flex_third_col}>
          <p className={styles.footer_name}> Qualis Events LLC. </p>
          <p className={styles.footer_text}>info@qualisevents.com</p>
        </div>
        <div className={styles.flex_third} style={{ justifyContent: "center" }}>
          <FontAwesomeIcon icon={faInstagram} className={styles.footer_icon} />
          <FontAwesomeIcon icon={faFacebookF} className={styles.footer_icon} />
          <FontAwesomeIcon icon={faEtsy} className={styles.footer_icon} />
          <FontAwesomeIcon icon={faPinterestP} className={styles.footer_icon} />
        </div>
        <div className={styles.flex_third} />
      </footer>
    </div>
  );
}
